services:
  - docker
before_script:
  - |
    docker run -it -d \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME=${DOCKER_USERNAME} \
      -e DOCKER_PASSWORD=${DOCKER_PASSWORD} \
      -e GITHUB_URL=${GITHUB_URL} \
      --name sample-java \
      tc420/sample-java:latest
script:
  - docker exec sample-java /stages/01_clone.sh
  - docker exec sample-java /stages/02_build.sh
  - docker exec sample-java /stages/03_test.sh
  - docker exec sample-java /stages/04_archive.sh
